require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Dictionaries::InstitutionsController do

  # This should return the minimal set of attributes required to create a valid
  # Dictionaries::Institution. As you add validations to Dictionaries::Institution, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "caption": "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Dictionaries::InstitutionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dictionaries_institutions as @dictionaries_institutions" do
      institution = Dictionaries::Institution.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dictionaries_institutions).should eq([institution])
    end
  end

  describe "GET show" do
    it "assigns the requested dictionaries_institution as @dictionaries_institution" do
      institution = Dictionaries::Institution.create! valid_attributes
      get :show, {id: institution.to_param}, valid_session
      assigns(:dictionaries_institution).should eq(institution)
    end
  end

  describe "GET new" do
    it "assigns a new dictionaries_institution as @dictionaries_institution" do
      get :new, {}, valid_session
      assigns(:dictionaries_institution).should be_a_new(Dictionaries::Institution)
    end
  end

  describe "GET edit" do
    it "assigns the requested dictionaries_institution as @dictionaries_institution" do
      institution = Dictionaries::Institution.create! valid_attributes
      get :edit, {id: institution.to_param}, valid_session
      assigns(:dictionaries_institution).should eq(institution)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dictionaries::Institution" do
        expect {
          post :create, {dictionaries_institution: valid_attributes}, valid_session
        }.to change(Dictionaries::Institution, :count).by(1)
      end

      it "assigns a newly created dictionaries_institution as @dictionaries_institution" do
        post :create, {dictionaries_institution: valid_attributes}, valid_session
        assigns(:dictionaries_institution).should be_a(Dictionaries::Institution)
        assigns(:dictionaries_institution).should be_persisted
      end

      it "redirects to the created dictionaries_institution" do
        post :create, {dictionaries_institution: valid_attributes}, valid_session
        response.should redirect_to(Dictionaries::Institution.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dictionaries_institution as @dictionaries_institution" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Institution.any_instance.stub(:save).and_return(false)
        post :create, {dictionaries_institution: { "caption": "invalid value" }}, valid_session
        assigns(:dictionaries_institution).should be_a_new(Dictionaries::Institution)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Institution.any_instance.stub(:save).and_return(false)
        post :create, {dictionaries_institution: { "caption": "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dictionaries_institution" do
        institution = Dictionaries::Institution.create! valid_attributes
        # Assuming there are no other dictionaries_institutions in the database, this
        # specifies that the Dictionaries::Institution created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dictionaries::Institution.any_instance.should_receive(:update).with({ "caption": "MyString" })
        put :update, {id: institution.to_param, dictionaries_institution: { "caption": "MyString" }}, valid_session
      end

      it "assigns the requested dictionaries_institution as @dictionaries_institution" do
        institution = Dictionaries::Institution.create! valid_attributes
        put :update, {id: institution.to_param, dictionaries_institution: valid_attributes}, valid_session
        assigns(:dictionaries_institution).should eq(institution)
      end

      it "redirects to the dictionaries_institution" do
        institution = Dictionaries::Institution.create! valid_attributes
        put :update, {id: institution.to_param, dictionaries_institution: valid_attributes}, valid_session
        response.should redirect_to(institution)
      end
    end

    describe "with invalid params" do
      it "assigns the dictionaries_institution as @dictionaries_institution" do
        institution = Dictionaries::Institution.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Institution.any_instance.stub(:save).and_return(false)
        put :update, {id: institution.to_param, dictionaries_institution: { "caption": "invalid value" }}, valid_session
        assigns(:dictionaries_institution).should eq(institution)
      end

      it "re-renders the 'edit' template" do
        institution = Dictionaries::Institution.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Institution.any_instance.stub(:save).and_return(false)
        put :update, {id: institution.to_param, dictionaries_institution: { "caption": "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dictionaries_institution" do
      institution = Dictionaries::Institution.create! valid_attributes
      expect {
        delete :destroy, {id: institution.to_param}, valid_session
      }.to change(Dictionaries::Institution, :count).by(-1)
    end

    it "redirects to the dictionaries_institutions list" do
      institution = Dictionaries::Institution.create! valid_attributes
      delete :destroy, {id: institution.to_param}, valid_session
      response.should redirect_to(dictionaries_institutions_url)
    end
  end

end
