require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Dictionaries::JournalsController do

  # This should return the minimal set of attributes required to create a valid
  # Dictionaries::Journal. As you add validations to Dictionaries::Journal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "caption" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Dictionaries::JournalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dictionaries_journals as @dictionaries_journals" do
      journal = Dictionaries::Journal.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dictionaries_journals).should eq([journal])
    end
  end

  describe "GET show" do
    it "assigns the requested dictionaries_journal as @dictionaries_journal" do
      journal = Dictionaries::Journal.create! valid_attributes
      get :show, {:id => journal.to_param}, valid_session
      assigns(:dictionaries_journal).should eq(journal)
    end
  end

  describe "GET new" do
    it "assigns a new dictionaries_journal as @dictionaries_journal" do
      get :new, {}, valid_session
      assigns(:dictionaries_journal).should be_a_new(Dictionaries::Journal)
    end
  end

  describe "GET edit" do
    it "assigns the requested dictionaries_journal as @dictionaries_journal" do
      journal = Dictionaries::Journal.create! valid_attributes
      get :edit, {:id => journal.to_param}, valid_session
      assigns(:dictionaries_journal).should eq(journal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dictionaries::Journal" do
        expect {
          post :create, {:dictionaries_journal => valid_attributes}, valid_session
        }.to change(Dictionaries::Journal, :count).by(1)
      end

      it "assigns a newly created dictionaries_journal as @dictionaries_journal" do
        post :create, {:dictionaries_journal => valid_attributes}, valid_session
        assigns(:dictionaries_journal).should be_a(Dictionaries::Journal)
        assigns(:dictionaries_journal).should be_persisted
      end

      it "redirects to the created dictionaries_journal" do
        post :create, {:dictionaries_journal => valid_attributes}, valid_session
        response.should redirect_to(Dictionaries::Journal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dictionaries_journal as @dictionaries_journal" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Journal.any_instance.stub(:save).and_return(false)
        post :create, {:dictionaries_journal => { "caption" => "invalid value" }}, valid_session
        assigns(:dictionaries_journal).should be_a_new(Dictionaries::Journal)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Journal.any_instance.stub(:save).and_return(false)
        post :create, {:dictionaries_journal => { "caption" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dictionaries_journal" do
        journal = Dictionaries::Journal.create! valid_attributes
        # Assuming there are no other dictionaries_journals in the database, this
        # specifies that the Dictionaries::Journal created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dictionaries::Journal.any_instance.should_receive(:update).with({ "caption" => "MyString" })
        put :update, {:id => journal.to_param, :dictionaries_journal => { "caption" => "MyString" }}, valid_session
      end

      it "assigns the requested dictionaries_journal as @dictionaries_journal" do
        journal = Dictionaries::Journal.create! valid_attributes
        put :update, {:id => journal.to_param, :dictionaries_journal => valid_attributes}, valid_session
        assigns(:dictionaries_journal).should eq(journal)
      end

      it "redirects to the dictionaries_journal" do
        journal = Dictionaries::Journal.create! valid_attributes
        put :update, {:id => journal.to_param, :dictionaries_journal => valid_attributes}, valid_session
        response.should redirect_to(journal)
      end
    end

    describe "with invalid params" do
      it "assigns the dictionaries_journal as @dictionaries_journal" do
        journal = Dictionaries::Journal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Journal.any_instance.stub(:save).and_return(false)
        put :update, {:id => journal.to_param, :dictionaries_journal => { "caption" => "invalid value" }}, valid_session
        assigns(:dictionaries_journal).should eq(journal)
      end

      it "re-renders the 'edit' template" do
        journal = Dictionaries::Journal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Journal.any_instance.stub(:save).and_return(false)
        put :update, {:id => journal.to_param, :dictionaries_journal => { "caption" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dictionaries_journal" do
      journal = Dictionaries::Journal.create! valid_attributes
      expect {
        delete :destroy, {:id => journal.to_param}, valid_session
      }.to change(Dictionaries::Journal, :count).by(-1)
    end

    it "redirects to the dictionaries_journals list" do
      journal = Dictionaries::Journal.create! valid_attributes
      delete :destroy, {:id => journal.to_param}, valid_session
      response.should redirect_to(dictionaries_journals_url)
    end
  end

end
