require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Dictionaries::PublishersController do

  # This should return the minimal set of attributes required to create a valid
  # Dictionaries::Publisher. As you add validations to Dictionaries::Publisher, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "caption" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Dictionaries::PublishersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dictionaries_publishers as @dictionaries_publishers" do
      publisher = Dictionaries::Publisher.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dictionaries_publishers).should eq([publisher])
    end
  end

  describe "GET show" do
    it "assigns the requested dictionaries_publisher as @dictionaries_publisher" do
      publisher = Dictionaries::Publisher.create! valid_attributes
      get :show, {:id => publisher.to_param}, valid_session
      assigns(:dictionaries_publisher).should eq(publisher)
    end
  end

  describe "GET new" do
    it "assigns a new dictionaries_publisher as @dictionaries_publisher" do
      get :new, {}, valid_session
      assigns(:dictionaries_publisher).should be_a_new(Dictionaries::Publisher)
    end
  end

  describe "GET edit" do
    it "assigns the requested dictionaries_publisher as @dictionaries_publisher" do
      publisher = Dictionaries::Publisher.create! valid_attributes
      get :edit, {:id => publisher.to_param}, valid_session
      assigns(:dictionaries_publisher).should eq(publisher)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dictionaries::Publisher" do
        expect {
          post :create, {:dictionaries_publisher => valid_attributes}, valid_session
        }.to change(Dictionaries::Publisher, :count).by(1)
      end

      it "assigns a newly created dictionaries_publisher as @dictionaries_publisher" do
        post :create, {:dictionaries_publisher => valid_attributes}, valid_session
        assigns(:dictionaries_publisher).should be_a(Dictionaries::Publisher)
        assigns(:dictionaries_publisher).should be_persisted
      end

      it "redirects to the created dictionaries_publisher" do
        post :create, {:dictionaries_publisher => valid_attributes}, valid_session
        response.should redirect_to(Dictionaries::Publisher.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dictionaries_publisher as @dictionaries_publisher" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Publisher.any_instance.stub(:save).and_return(false)
        post :create, {:dictionaries_publisher => { "caption" => "invalid value" }}, valid_session
        assigns(:dictionaries_publisher).should be_a_new(Dictionaries::Publisher)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Publisher.any_instance.stub(:save).and_return(false)
        post :create, {:dictionaries_publisher => { "caption" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dictionaries_publisher" do
        publisher = Dictionaries::Publisher.create! valid_attributes
        # Assuming there are no other dictionaries_publishers in the database, this
        # specifies that the Dictionaries::Publisher created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dictionaries::Publisher.any_instance.should_receive(:update).with({ "caption" => "MyString" })
        put :update, {:id => publisher.to_param, :dictionaries_publisher => { "caption" => "MyString" }}, valid_session
      end

      it "assigns the requested dictionaries_publisher as @dictionaries_publisher" do
        publisher = Dictionaries::Publisher.create! valid_attributes
        put :update, {:id => publisher.to_param, :dictionaries_publisher => valid_attributes}, valid_session
        assigns(:dictionaries_publisher).should eq(publisher)
      end

      it "redirects to the dictionaries_publisher" do
        publisher = Dictionaries::Publisher.create! valid_attributes
        put :update, {:id => publisher.to_param, :dictionaries_publisher => valid_attributes}, valid_session
        response.should redirect_to(publisher)
      end
    end

    describe "with invalid params" do
      it "assigns the dictionaries_publisher as @dictionaries_publisher" do
        publisher = Dictionaries::Publisher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Publisher.any_instance.stub(:save).and_return(false)
        put :update, {:id => publisher.to_param, :dictionaries_publisher => { "caption" => "invalid value" }}, valid_session
        assigns(:dictionaries_publisher).should eq(publisher)
      end

      it "re-renders the 'edit' template" do
        publisher = Dictionaries::Publisher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionaries::Publisher.any_instance.stub(:save).and_return(false)
        put :update, {:id => publisher.to_param, :dictionaries_publisher => { "caption" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dictionaries_publisher" do
      publisher = Dictionaries::Publisher.create! valid_attributes
      expect {
        delete :destroy, {:id => publisher.to_param}, valid_session
      }.to change(Dictionaries::Publisher, :count).by(-1)
    end

    it "redirects to the dictionaries_publishers list" do
      publisher = Dictionaries::Publisher.create! valid_attributes
      delete :destroy, {:id => publisher.to_param}, valid_session
      response.should redirect_to(dictionaries_publishers_url)
    end
  end

end
