require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SecurityClassificationsController do

  # This should return the minimal set of attributes required to create a valid
  # SecurityClassification. As you add validations to SecurityClassification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "caption": "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SecurityClassificationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all security_classifications as @security_classifications" do
      security_classification = SecurityClassification.create! valid_attributes
      get :index, {}, valid_session
      assigns(:security_classifications).should eq([security_classification])
    end
  end

  describe "GET show" do
    it "assigns the requested security_classification as @security_classification" do
      security_classification = SecurityClassification.create! valid_attributes
      get :show, {id: security_classification.to_param}, valid_session
      assigns(:security_classification).should eq(security_classification)
    end
  end

  describe "GET new" do
    it "assigns a new security_classification as @security_classification" do
      get :new, {}, valid_session
      assigns(:security_classification).should be_a_new(SecurityClassification)
    end
  end

  describe "GET edit" do
    it "assigns the requested security_classification as @security_classification" do
      security_classification = SecurityClassification.create! valid_attributes
      get :edit, {id: security_classification.to_param}, valid_session
      assigns(:security_classification).should eq(security_classification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SecurityClassification" do
        expect {
          post :create, {security_classification: valid_attributes}, valid_session
        }.to change(SecurityClassification, :count).by(1)
      end

      it "assigns a newly created security_classification as @security_classification" do
        post :create, {security_classification: valid_attributes}, valid_session
        assigns(:security_classification).should be_a(SecurityClassification)
        assigns(:security_classification).should be_persisted
      end

      it "redirects to the created security_classification" do
        post :create, {security_classification: valid_attributes}, valid_session
        response.should redirect_to(SecurityClassification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved security_classification as @security_classification" do
        # Trigger the behavior that occurs when invalid params are submitted
        SecurityClassification.any_instance.stub(:save).and_return(false)
        post :create, {security_classification: { "caption": "invalid value" }}, valid_session
        assigns(:security_classification).should be_a_new(SecurityClassification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SecurityClassification.any_instance.stub(:save).and_return(false)
        post :create, {security_classification: { "caption": "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested security_classification" do
        security_classification = SecurityClassification.create! valid_attributes
        # Assuming there are no other security_classifications in the database, this
        # specifies that the SecurityClassification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SecurityClassification.any_instance.should_receive(:update).with({ "caption": "MyString" })
        put :update, {id: security_classification.to_param, security_classification: { "caption": "MyString" }}, valid_session
      end

      it "assigns the requested security_classification as @security_classification" do
        security_classification = SecurityClassification.create! valid_attributes
        put :update, {id: security_classification.to_param, security_classification: valid_attributes}, valid_session
        assigns(:security_classification).should eq(security_classification)
      end

      it "redirects to the security_classification" do
        security_classification = SecurityClassification.create! valid_attributes
        put :update, {id: security_classification.to_param, security_classification: valid_attributes}, valid_session
        response.should redirect_to(security_classification)
      end
    end

    describe "with invalid params" do
      it "assigns the security_classification as @security_classification" do
        security_classification = SecurityClassification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SecurityClassification.any_instance.stub(:save).and_return(false)
        put :update, {id: security_classification.to_param, security_classification: { "caption": "invalid value" }}, valid_session
        assigns(:security_classification).should eq(security_classification)
      end

      it "re-renders the 'edit' template" do
        security_classification = SecurityClassification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SecurityClassification.any_instance.stub(:save).and_return(false)
        put :update, {id: security_classification.to_param, security_classification: { "caption": "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested security_classification" do
      security_classification = SecurityClassification.create! valid_attributes
      expect {
        delete :destroy, {id: security_classification.to_param}, valid_session
      }.to change(SecurityClassification, :count).by(-1)
    end

    it "redirects to the security_classifications list" do
      security_classification = SecurityClassification.create! valid_attributes
      delete :destroy, {id: security_classification.to_param}, valid_session
      response.should redirect_to(security_classifications_url)
    end
  end

end
